puts "How To Do The Macarena:"
"Step 1: Right arm out in front of you, palm facing down."
"Step 2: Left arm out in front of you, palm facing down."
"Step 3: Turn your right palm up."
"Step 4: Turn your left palm up."
"Step 5: Place your right hand on your left shoulder."
"Step 6: Place your left hand on your right shoulder."
"Step 7: Bring your right hand up and around to the back of your head."
"Step 8: Bring your left hand up and around to the back of your head."